name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Java ${{matrix.java-version}}
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: ${{matrix.java-version}}
      - name: Run tests
        run: ./mvnw --batch-mode --no-transfer-progress -e test

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create code coverage report
        run: ./mvnw --batch-mode --no-transfer-progress -e test jacoco:report
      - name: Upload code coverage report
        uses: codecov/codecov-action@v5
        with:
          files: target/site/jacoco/jacoco.xml
          name: codecov

  dependency-check:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check dependencies
        run: ./mvnw --batch-mode --no-transfer-progress -e dependency-check:check -DnvdApiKey='${{ secrets.NVD_API_KEY }}' -DossIndexUsername='${{ secrets.OSSINDEX_USERNAME }}' -DossIndexPassword='${{ secrets.OSSINDEX_TOKEN }}'