name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 10a, 11, 12a, 13a, 14a, 15a, 16a, 17, 18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Split Java version & distribution
        id: java
        run: |
          [[ "${{matrix.java-version}}" =~ .*a$ ]] && distribution='adopt' || distribution='temurin'
          echo "::set-output name=distribution::$distribution"
          version=$(echo ${{matrix.java-version}} | sed 's/a$//')
          echo "::set-output name=version::$version"
      - name: Set up Java ${{steps.java.outputs.version}}
        uses: actions/setup-java@v3
        with:
          distribution: ${{steps.java.outputs.distribution}}
          java-version: ${{steps.java.outputs.version}}
      - name: Run tests
        run: mvn -e test -Dmaven.wagon.http.ssl.insecure=${{ steps.java.outputs.version == 9 || steps.java.outputs.version == 10 }}

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create code coverage report
        run: mvn -e test jacoco:report
      - name: Upload code coverage report
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
          name: codecov
